### ISSUE TITLE
Hear own footateps

### ISSUE THREAD

**Issue by plainbum** [zenakuten/WS3SPN#1]
I have " Play on footsteps sound" is checked and I still hear my footsteps.
![20240612_100946](https://github.com/zenakuten/WS3SPN/assets/110470192/16fedbe7-72c7-4767-88f1-a1920f1e9c41)

**Comment by zenakuten** [comment]
You have to disable 'weapon bob' in the regular game settings for unchecking 'play own footsteps' to work.

If you hover over 'play own footsteps' the tool tip mentions this.

**Comment by zenakuten** [comment]
This is a limitation in the base engine code.  I could also disable weapon bob when this item is unchecked, but what happens if I re-check it?  They are separate settings.  I don't believe it should re-enable weapon bob.

I think for correct behavior I would need to add 'weapon bob' check box to this same screen, and make 'play own footsteps' a sub-checkbox underneath it.   Either way would be confusing I think.  They really shouldn't be tied together, but again it's in the base engine that way.

**Comment by zenakuten** [comment]
Since the tooltip explains how to use this correctly, I'm closing as won't fix.

**Comment by plainbum** [comment]
It is working now, I must have had to close then open the game  OR reboot my computer.
Its is working now, no footsteps since the reboot.
Thanks!!
    On Saturday, June 15, 2024 at 09:27:53 AM CDT, zenakuten ***@***.***> wrote:  
 
 


Since the tooltip explains how to use this correctly, I'm closing as won't fix.
